spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://2022cs056:dH4aTFn3IOerWlVZ@cluster0.9ccambx.mongodb.net/islandhop_trips?retryWrites=true&w=majority}
      database: islandhop_trips
  datasource:
    url: jdbc:postgresql://db.hgpicovzphnrhsdhggqs.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: islandhop123#
    driver-class-name: org.postgresql.Driver

google:
  maps:
    api-key: AIzaSyCCk35BJWjRvG7KHskc0GETOWe0qrBE-Go

logging:
  level:
    root: INFO
    com.islandhop.tripinit: DEBUG

server:
  port: 8095
  servlet:
    context-path: /api

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
