version: '3.8'

services:
  payhere-payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - PAYHERE_MERCHANT_ID=${PAYHERE_MERCHANT_ID:-1234567}
      - PAYHERE_SECRET=${PAYHERE_SECRET:-your-secret-key}
      - PAYHERE_NOTIFY_URL=${PAYHERE_NOTIFY_URL:-http://localhost:8088/api/v1/payments/notify}
      - PAYHERE_SANDBOX=${PAYHERE_SANDBOX:-true}
    networks:
      - islandhop-network

networks:
  islandhop-network:
    driver: bridge
