version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: tourism
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: tourism
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    restart: always