spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourism
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

redis:
  host: localhost
  port: 6379
  password:

firebase:
  project-id: your-local-firebase-project-id
  database-url: https://your-local-firebase-db-url
  api-key: your-local-firebase-api-key
  client-email: your-local-firebase-client-email
  private-key: your-local-firebase-private-key

aws:
  sns:
    region: us-east-1
    access-key: your-local-aws-access-key
    secret-key: your-local-aws-secret-key

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework: INFO
    com.tourism.userservices: DEBUG
