spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/islandhop_trips
      database: islandhop_trips
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/your_postgres_db
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

google:
  maps:
    api-key: your_google_maps_api_key

logging:
  level:
    root: INFO
    com.islandhop.tripinitiation: DEBUG
  file:
    name: logs/trip_initiation_service.log
    max-size: 10MB
    max-history: 30