version: '3.8'

services:
  # Trip Planning Service (connects to MongoDB Atlas)
  trip-planning-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: islandhop-trip-planning
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      # MongoDB Atlas Configuration
      MONGODB_URI: ${MONGODB_URI:-mongodb+srv://2022cs056:dH4aTFn3IOerWlVZ@cluster0.9ccambx.mongodb.net/islandhop_trips?retryWrites=true&w=majority}
      
      # User Services Integration
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL:-http://host.docker.internal:8081/api}
      
      # External API Keys
      TRIPADVISOR_API_KEY: ${TRIPADVISOR_API_KEY:-your-tripadvisor-key}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY:-your-google-places-key}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-your-google-maps-key}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY:-your-weather-key}
      
      # Service Configuration
      SERVER_PORT: ${SERVER_PORT:-8083}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
      
      # JVM Options
      JAVA_OPTS: "${JAVA_OPTS:--Xmx1024m -Xms512m -XX:+UseG1GC}"
      
      # Logging
      LOGGING_LEVEL_COM_ISLANDHOP: ${LOGGING_LEVEL_COM_ISLANDHOP:-DEBUG}
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT:-INFO}
      
      # Recommendation Algorithm Settings
      RECOMMENDATION_MAX_DAILY_TRAVEL_HOURS: ${RECOMMENDATION_MAX_DAILY_TRAVEL_HOURS:-8}
      RECOMMENDATION_MAX_ATTRACTIONS_PER_DAY: ${RECOMMENDATION_MAX_ATTRACTIONS_PER_DAY:-4}
      RECOMMENDATION_SIMILARITY_THRESHOLD: ${RECOMMENDATION_SIMILARITY_THRESHOLD:-0.7}
      
    networks:
      - islandhop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/trip/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  islandhop-network:
    driver: bridge
