version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: islandhop-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: islandhop_trips
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - islandhop-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Trip Planning Service
  trip-planning-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: islandhop-trip-planning
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      # MongoDB Configuration
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: islandhop_trips
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password123
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      
      # User Services Integration
      USER_SERVICE_BASE_URL: http://host.docker.internal:8081/api
      
      # External API Keys (set these in .env file)
      TRIPADVISOR_API_KEY: ${TRIPADVISOR_API_KEY:-your-tripadvisor-key}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-your-google-maps-key}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY:-your-weather-key}
      
      # JVM Options
      JAVA_OPTS: "-Xmx1024m -Xms512m -XX:+UseG1GC"
      
      # Logging
      LOGGING_LEVEL_COM_ISLANDHOP: DEBUG
      LOGGING_LEVEL_ROOT: INFO
      
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - islandhop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/trip/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: islandhop-mongo-express
    restart: unless-stopped
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - islandhop-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  islandhop-network:
    driver: bridge
