database:
  url: jdbc:postgresql://<YOUR_POSTGRES_HOST>:<YOUR_POSTGRES_PORT>/<YOUR_DATABASE_NAME>
  username: <YOUR_DATABASE_USERNAME>
  password: <YOUR_DATABASE_PASSWORD>
  driver-class-name: org.postgresql.Driver

spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ml:
  model:
    endpoint: <YOUR_ML_MODEL_ENDPOINT>
    threshold: 0.5

server:
  port: 8080

logging:
  level:
    root: INFO
    com.islandhop.reviewservice: DEBUG